-- Run this in the Supabase SQL editor for the toeic-flashcards project.

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  word text not null,
  phonetic text,
  meanings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.words
  add column if not exists phonetic text;

alter table public.words
  add column if not exists meanings jsonb not null default '[]'::jsonb;

alter table public.words
  add column if not exists created_at timestamptz not null default now();

alter table public.words enable row level security;

drop policy if exists words_insert_all on public.words;
drop policy if exists words_update_all on public.words;
drop policy if exists words_delete_all on public.words;
drop policy if exists words_delete_public on public.words;
drop policy if exists words_insert_authenticated on public.words;
drop policy if exists words_update_authenticated on public.words;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'words'
      and policyname = 'words_select_all'
  ) then
    create policy words_select_all
      on public.words
      for select
      using (true);
  end if;
end $$;
